### PR TITLE
Replace assert_equal nil with assert_nil

### PR DESCRIPTION
**Pull request by jhawthorn**
Fixes all deprecation warnings in our tests

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Looks like a rebase is needed for this :)

**Comment by edwardmp** [comment]
this can be closed as already fixed by #390

**Comment by AlexVPopov** [comment]
@edwardmp Why do you think #390 has resolved this? I just cloned master and the warnings still appear. Besided #390 has not changed these assertions.

**Comment by edwardmp** [comment]
@AlexVPopov I'm sorry I linked the wrong pull request. The right one that fixes this is #389, which has been merged into master.

**Pull request closed without merging**
