### PR TITLE
Support dependent: :destroy

### LINKED ISSUE #507: Association is not restored when using dependent: :destroy_async
Rails 6.1 introduces the new option `dependent: :destroy_async` (see rails/rails#40157). When using Paranoia, the associations are soft deleted in the background job as they should be but are not restored properly.

### PR DESCRIPTION
**Pull request by pomartel**
Fixes #507

### CODE REVIEW

**Comment by pomartel** [comment]
This is more complicated than I first thought. Counter caches and permanent deletes also need to be handled correctly. I started implementing a custom `DestroyAssociationAsyncJob` but now I see that the gem maintainers don't accept new features so I will close this PR for now but I would be interested in digging deeper if there is a chance this feature can be accepted.

**Comment by mathieujobin** [comment]
@pomartel I am definitely interesting seeing `destroy_async` support in paranoia

**Comment by pomartel** [comment]
Sorry @mathieujobin, I opted to destroy records asynchronously in my own code instead (using a background job).

**Comment by mathieujobin** [comment]
No problem

It sounds like a good solution

**Pull request closed without merging**
