### PR TITLE
allow rails 7.0

### PR DESCRIPTION
**Pull request by mathieujobin**
Attempting an upgrade on Rails 7.
I need to bump this dependency.

### CODE REVIEW

**Comment by mathieujobin** [comment]
Build run : https://github.com/payrollhero/paranoia/actions/runs/1420873001

**Comment by mathieujobin** [comment]
@rubysherpas Any chance you could have a look at this PR ?

**Comment by mathieujobin** [comment]
@sevenseacat ^^ 

Thanks

**Comment by rickychilcott** [comment]
Thank you for all of your work on this and other PRs @mathieujobin! 

However, I'm not certain what is likely to happen with this one. Time will tell, but https://github.com/rubysherpas doesn't give much confidence that this account/organization is active. Moreover, http://rubysherpas.com/ is not an active domain any longer.

Since this has been open without any activity, have you considered officially forking and trying to maintain a different published gem? Or even more ideally, become maintainer of this gem?

@sevenseacat -- it looks likely you're working in Elixir these days so perhaps Ruby is no longer something you're excited to work in. Much appreciated for all of your work on this. Perhaps you could help provide some direction.

Thank you and happy holidays!

**Comment by mathieujobin** [comment]
I don't mind owning the gem, I inherited many already... https://rubygems.org/profiles/mathieu

but I would hate having to rename it, and to prevent that, I need push rights on rubygems.org

@rickychilcott  @rubysherpas @sevenseacat

**Comment by radar** [comment]
@mathieujobin Wish granted.

**Comment by radar** [comment]
v2.5.0 released with these changes.

I'll stop ignoring notifications on this project now.

**Comment by rickychilcott** [comment]
Thank you @radar

**Pull request merged**
