### PR TITLE
Supporting a bit more of the acts_as_paranoid public API

### PR DESCRIPTION
**Pull request by asanghi**
@radar ,

Hey buddy! Not sure if the goal of the project is to remain lean or be a drop in replacement for the acts_as_paranoid, so I'm requesting you to consider supporting find_with_deleted. Please consider. Let me know if you want this modified in some way?

Added tests too!

Cheers

### CODE REVIEW

**Comment by radar** [comment]
I would rather people just used the `unscoped` method for this one. Although, if it's for backward compatibility, sure, why not? Can I ask why you didn't just alias the method?

**Comment by asanghi** [comment]
Firstly, i think i added this at the wrong spot! We only want find_with_deleted when we include Paranoia. Will fix this.

I'm dyslexic in so far that i can never remember which method goes first in alias so i tend to overlook it. 
Same with using `ln -s` on unix. I'll try with alias.

Also in the same vein. I was going to send a pull for `find_only_deleted` but no more :)
We're transitioning an older app to Rails 3 and i'd rather use paranoia and hopefully make it a drop in as far as our API dependency on the older acts_as_paranoid.

**Comment by asanghi** [comment]
i tried `alias :find_with_deleted :unscoped` but that doesn't work because `unscoped` is not a method on AR::Base.

**Comment by asanghi** [comment]
Bah! The older API supported :all, :every and just one with `find_with_deleted` and `find_only_deleted`. 

So my pull isnt exactly backwards compatible. Sorry for the bother!

**Comment by radar** [comment]
Perhaps you could add a note to the readme that if people want this functionality they could use `unscoped` and `unscoped.where("deleted_at IS NOT NULL")` respectively?

**Pull request closed without merging**
