### PR TITLE
Allow activerecord 6.0

### PR DESCRIPTION
**Pull request by iggant**
We are trying to test our application on rails 6.0.0.alpha but we can't install this because of the version lock
Probably this will be helpful that we can try and report any issues with edge rails

### CODE REVIEW

**Comment by jarednorman** [comment]
@jhawthorn The test suite for `solidus_core` passes with this branch of paranoia, so it's probably safe to merge and cut a release.

**Comment by jhawthorn** [comment]
@jarednorman I don't want to remove the upper dependency altogether. This gem is guaranteed to break on some future rails version. But I would be happy to bump it to < 6.1

**Comment by jarednorman** [comment]
Sure, I can PR a change to do that. 👍

**Comment by iggant** [comment]
@jhawthorn done, also since rails 6.0 now support only ruby 2.5 exclude all below, 
Also add ruby 2.6.1 (escape 2.6.0 since it has a bug in http), of course this don't do anything with current gem but anyway

**Comment by jarednorman** [comment]
Awesome, this should be good to go then. 🤘

**Review by matheusbn — APPROVED** [review]

**Comment by iggant** [comment]
@matheusbn  resolved conflict so it can be merged now

**Comment by jarednorman** [comment]
@jhawthorn I think this one is good, except for the CI issues, which are unrelated.

**Pull request closed without merging**
