### PR TITLE
Add ability to have types other than datetime and add boolean type.

### PR DESCRIPTION
**Pull request by aselder**
This allows an optional :type option to be passed to acts_as_paranoid.
The allowed types are :datetime (the default), and :boolean. If the
column type is boolean, true will be written to the attribute rather
than the date/time.

It should follow all the same behavior as the datetime version, except
for callbacks. The default implementation uses AR::Base#touch which
fires after_touch, after_commit, and after_rollback callbacks. The
boolean version uses update_column which fires no call backs. I
couldn't find an equivalent method for a non-datetime field.

### CODE REVIEW

**Comment by radar** [comment]
What is the point of this? In what case would you want to have a boolean? How is this useful for others who use this library?

**Comment by aselder** [comment]
We have existing data schemas that use a boolean column (is_deleted) to denote soft deleted records rather than a datetime column. This allows user to use a column of some other type rather than only a date time

**Comment by radar** [comment]
Run a migration which converts the booleans to datetimes, where the time is the current time.

Alternatively, maintain a fork.

**Comment by aselder** [comment]
Remember, not everybody has control of their schemas. I'll just maintain a fork, but thought this ability might be useful to others.

**Pull request closed without merging**
