### PR TITLE
Use update_column and where.not

### PR DESCRIPTION
**Pull request by delba**

### CODE REVIEW

**Comment by radar** [comment]
Hey @delba, could you please check on these build failures? https://travis-ci.org/radar/paranoia/builds/7835512

**Comment by delba** [comment]
@radar Travis was testing against Rails versions lower than 4. I updated the gemspec file to use activerecord versions higher than 4.0.0.beta1.

**Comment by delba** [comment]
@radar Should I close this pull request https://github.com/radar/paranoia/pull/58?

**Comment by radar** [comment]
Yes, I think closing #58 is the right thing to do.

**Comment by radar** [comment]
Build is green and code looks clean. Merging :)

**Pull request merged**
