### PR TITLE
Version 2.2.0

### PR DESCRIPTION
**Pull request by jhawthorn**

### CODE REVIEW

**Comment by sanemat** [comment]
@jhawthorn Would you push v2.2.0 git tag to GitHub?
https://github.com/rubysherpas/paranoia/releases

**Comment by BenMorganIO** [comment]
@sanemat thanks for asking. Hope this helps:

https://github.com/rubysherpas/paranoia/releases/tag/2.2.0

**Comment by jhawthorn** [comment]
Thanks @BenMorganIO forgot to follow up on this (and the github perms didn't allow me to push directly)

**Comment by sanemat** [comment]
@BenMorganIO @jhawthorn thanks!

**Pull request merged**
