### PR TITLE
Added without_default_scope option

### PR DESCRIPTION
**Pull request by westonganger**
I added an option to skip the default_scope. This makes the gem much more versatile and not susceptible to all the problems that come with default_scope.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Thank you @westonganger. I love this.

Is it possible to add a test?

**Comment by westonganger** [comment]
I have added a test for this.

**Comment by jhawthorn** [comment]
Awesome. Thanks.

**Comment by reicheltd** [comment]
Works thx. Had to move from 2.1 to current rails4 branch.

**Comment by jrochkind** [comment]
Hi, I could really use this feature, will a paranoia 2.2 with it included be released anytime soon?

**Comment by jrochkind** [comment]
FWIW, for others coming across this, here's how I monkey-patched it in, roughly, in the specific class where I needed it...

```
    acts_as_paranoid without_default_scope: true

  paranoia_spec = Gem.loaded_specs["paranoia"]
  if paranoia_spec.version < Gem::Version.new('2.2')
    default_scopes.delete_if do |scope|
      scope.source_location.first.start_with? paranoia_spec.full_gem_path
    end
    class << self; alias_method :without_deleted, :paranoia_scope end
  end
```

**Pull request merged**
