### PR TITLE
Fix for #122, #121 and #175 on Rails 4 branch

### PR DESCRIPTION
**Pull request by codeodor**
I wasn't sure whether #121 got closed because this fix wasn't desired for the Rails 4 branch, or just because it was so similar to #122 that it looked like a duplicate, so while I was fixing [the issue brought up](https://github.com/radar/paranoia/pull/122#issuecomment-113934008) by @joshuapinter I thought I'd add the test for the Rails 4 branch as well.

### CODE REVIEW

**Comment by codeodor** [comment]
For what it's worth, this test that's failing on travis fails before this change. If I `git checkout HEAD~3` from where it's at now, and run against jruby, it results in the same failure.

**Comment by codeodor** [comment]
But I fixed it anyway. That last commit should do it.

**Comment by radar** [comment]
Thanks @codeodor!

**Comment by codeodor** [comment]
My pleasure! :+1:

**Pull request merged**
