### PR TITLE
Support an additional boolean column to enable unique key enforcement

### PR DESCRIPTION
**Pull request by n3bulous**
Provide support for handling a boolean column on tables with deleted_at so unique keys can be enforced (null values in a unique key do not allow enforcement of the unique key)

### CODE REVIEW

**Comment by radar** [comment]
Looks good to me. Thanks @n3bulous :)

**Comment by radar** [comment]
@n3bulous Would you like to create a PR for the rails3 branch as well?

**Comment by n3bulous** [comment]
I can do that after vacation :)

**Comment by radar** [comment]
Excellent, thank you :)

**Comment by n3bulous** [comment]
I also need to update the documentation a bit.  The index example should list :is_deleted first in the composite key.

**Pull request closed without merging**
